# Generated by Django 4.1.2 on 2022-10-09 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Genres', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genres',
            new_name='Genre',
        ),
    ]
