# Generated by Django 4.1.2 on 2022-10-09 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Series', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher_series',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Series'),
        ),
    ]
